# Generated by Django 5.2.3 on 2025-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auto_modelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Automobilio modelis', max_length=200, verbose_name='Markė')),
                ('make', models.CharField(help_text='Modelis', max_length=200, verbose_name='Markė')),
            ],
        ),
    ]
