# Generated by Django 5.2.3 on 2025-07-01 14:15

import datetime
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Automobilio gamintojas', max_length=200, verbose_name='Gamintojas')),
                ('model', models.CharField(help_text='Automobilio modelis', max_length=200, verbose_name='Modelis')),
                ('year', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Pagaminimo metai')),
            ],
            options={
                'verbose_name': 'automobilio modelis',
                'verbose_name_plural': 'Automobilių modeliai',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Suteiktos paslaugos aprašymas', max_length=200, verbose_name='Paslaugos pavadinimas')),
                ('price', models.FloatField(max_length=10, verbose_name='Paslaugos kaina')),
            ],
            options={
                'verbose_name': 'paslauga',
                'verbose_name_plural': 'paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_plate', models.CharField(help_text='Automobilio valstybinis NR', max_length=6, verbose_name='Valstybinis NR')),
                ('vin_code', models.CharField(help_text='Automobilio kėbulo numeris', max_length=17, verbose_name='VIN numeris')),
                ('description', tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='Automobilio aprašymas')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='CarPic')),
                ('automodel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservisas.automodel', verbose_name='Automobilio modelis')),
            ],
            options={
                'verbose_name': 'automobilis',
                'verbose_name_plural': 'automobiliai',
            },
        ),
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Užsakymo data')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Remonto terminas (data)')),
                ('deadline_time', models.TimeField(blank=True, null=True, verbose_name='Remonto terminals (laikas)')),
                ('status', models.CharField(blank=True, choices=[('l', 'Laukiama'), ('v', 'Vykdoma'), ('n', 'Neapmokėta'), ('i', 'Įvykdyta'), ('x', 'Atšaukta')], default='l', max_length=1, verbose_name='Būsena')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='autoservisas.auto', verbose_name='Automobilis')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Klientas')),
            ],
            options={
                'verbose_name': 'užsakymas',
                'verbose_name_plural': 'užsakymai',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('content', models.TextField(max_length=500, verbose_name='Komentaras')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='autoservisas.orderdata')),
            ],
            options={
                'verbose_name': 'komentaras',
                'verbose_name_plural': 'komentarai',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics', verbose_name='Nuotrauka')),
                ('is_employee', models.BooleanField(default=False, verbose_name='darbuotojas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True, verbose_name='Kiekis')),
                ('order_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservisas.orderdata', verbose_name='Užsakymas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservisas.service', verbose_name='Suteikta paslauga')),
            ],
            options={
                'verbose_name': 'užsakymo įrašas',
                'verbose_name_plural': 'užsakymo įrašai',
            },
        ),
    ]
