# Generated by Django 5.2.3 on 2025-06-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auto_modelis',
            new_name='AutoModel',
        ),
    ]
