# Generated by Django 5.2.3 on 2025-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0003_remove_automodel_owner_auto_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='customer',
        ),
    ]
