# Generated by Django 5.2.3 on 2025-06-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_service_orderdata_orderline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'automobilis', 'verbose_name_plural': 'automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='automodel',
            options={'verbose_name': 'automobilio modelis', 'verbose_name_plural': 'Automobilių modeliai'},
        ),
        migrations.AlterModelOptions(
            name='orderdata',
            options={'verbose_name': 'užsakymas', 'verbose_name_plural': 'užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'užsakymo eilutė', 'verbose_name_plural': 'užsakymo eilutės'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'paslauga', 'verbose_name_plural': 'paslaugos'},
        ),
        migrations.AddField(
            model_name='automodel',
            name='year',
            field=models.IntegerField(blank=True, default=None, max_length=4, null=True, verbose_name='Pagaminimo metai'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservisas.orderdata', verbose_name='Užsakymas'),
        ),
    ]
