# Generated by Django 5.2.3 on 2025-07-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0004_remove_orderdata_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Kiekis'),
        ),
    ]
