# Generated by Django 5.2.3 on 2025-06-16 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0005_alter_auto_options_alter_automodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'užsakymo įrašas', 'verbose_name_plural': 'užsakymo įrašai'},
        ),
        migrations.AlterField(
            model_name='automodel',
            name='make',
            field=models.CharField(help_text='Automobilio gamintojas', max_length=200, verbose_name='Gamintojas'),
        ),
        migrations.AlterField(
            model_name='automodel',
            name='model',
            field=models.CharField(help_text='Automobilio modelis', max_length=200, verbose_name='Modelis'),
        ),
        migrations.AlterField(
            model_name='automodel',
            name='year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Pagaminimo metai'),
        ),
    ]
