# Generated by Django 4.2.23 on 2025-07-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0005_alter_orderline_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autoservisas.auto', verbose_name='Automobilis'),
        ),
    ]
