# Generated by Django 4.2.23 on 2025-07-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_orderdata_deadline_alter_orderdata_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='deadline_time',
        ),
    ]
