# Generated by Django 5.2.3 on 2025-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_alter_orderline_options_alter_automodel_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='status',
            field=models.CharField(blank=True, choices=[('l', 'Laukiama'), ('v', 'Vykdoma'), ('n', 'Neapmokėta'), ('a', 'Apmokėta'), ('x', 'Atšaukta')], default='l', max_length=1, verbose_name='Būsena'),
        ),
    ]
