# Generated by Django 5.2.3 on 2025-06-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0007_orderdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='autoservisas.auto', verbose_name='Automobilis'),
        ),
    ]
